### ISSUE TITLE
建议增加一个搜索文章的啊

### ISSUE THREAD

**Issue by huchenghua** [num5/chca#1]

**Comment by num5** [comment]
我新增了一个缓存文章信息的方法，编译markdown的时候可以把所有的文章信息都放到一个json文件中，因为生成的是静态博客，搜索可以使用js实现以下。也可以使用百度的站内搜索。

**Comment by guhao022** [comment]
新增了一个缓存文章信息的方法，编译markdown的时候可以把所有的文章信息都放到一个json文件中，因为生成的是静态博客，搜索可以使用js实现以下。也可以使用百度的站内搜索。
